# -*- coding: utf-8 -*-
"""data_preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1puAmpNmI7JZk2JETWyPzSzAAK4LNhlDQ
"""

import joblib
import pandas as pd
from pandas import DataFrame

# load transformer dan feature columns
_transformer = joblib.load("model/featuretransformer.joblib")
FEATURE_COLUMNS = joblib.load("model/feature_columns.joblib")

def preprocess(df: DataFrame) -> pd.DataFrame:

    if list(df.columns) != FEATURE_COLUMNS:
        raise ValueError(
            f"Kolom DataFrame tidak sesuai.\nDiharapkan:\n{FEATURE_COLUMNS}\nDitemukan:\n{list(df.columns)}"
        )
   
    arr = _transformer.transform(df)
    new_cols = _transformer.get_feature_names_out(FEATURE_COLUMNS)
    
    return pd.DataFrame(arr, columns=new_cols)
